<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductMS.Data.Contracts\ProductMS.Data.Contracts.csproj" />
    <ProjectReference Include="..\ProductMS.DTOs\ProductMS.DTOs.csproj" />
    <ProjectReference Include="..\ProductMS.Framework\ProductMS.Framework.csproj" />
  </ItemGroup>

</Project>
