<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductMS.DTOs\ProductMS.DTOs.csproj" />
    <ProjectReference Include="..\ProductMS.Framework.Extensions\ProductMS.Framework.Extensions.csproj" />
  </ItemGroup>

</Project>
