<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="ResponseCodes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResponseCodes.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="ResponseCodes.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResponseCodes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
